### ISSUE TITLE
Het aantal dagen tussen 2 datums weergeven

### ISSUE THREAD

**Issue by Brabantplant** [RedAndBundle/ForNAVSupport#12]
Ik zou graag in een ForNav rapport het verschil tussen 2 datums willen weergeven. Het lukt me  niet om de juiste Javascript code te schrijven.

**Comment by renebrummel** [comment]
Hoi, dat kan. Datum calculatie is niet super eenvouding in JavaScript dus je moet er waarschijnlijk wat moeite voor doen.

Wat probeer je precies te doen? Het verschil in dagen tussen 2 data? Welke source expressions zijn dat in ForNAV?

**Comment by Brabantplant** [comment]
Eigenlijk probeer ik onderstaande te doen waarbij CustomColumn3 de startdatum van een activiteit is. In het mooiste geval komt hier een getal uit…

[Afbeelding met tekst, software, Multimediasoftware, schermopname  Automatisch gegenereerde beschrijving]

Met vriendelijke groet,

Justin Aerts
Hoofd Afdeling Planning


***@***.***

T:
+31 (0)6 83 53 85 70
E:
***@***.******@***.***>
W:
www.brabantplant.nl<http://www.brabantplant.nl/>

Disclaimer: De inhoud van dit bericht is uitsluitend bestemd voor de geadresseerde.
Gebruik van de inhoud van dit bericht door anderen zonder toestemming van Brabant Plant BV is onrechtmatig.
Mocht dit bericht ten onrechte bij u terecht komen, dan verzoeken wij u dit direct te melden aan de verzender en het bericht te vernietigen.
Aan de inhoud van dit bericht kunnen geen rechten worden ontleend.
Van: René Brummel ***@***.***>
Verzonden: dinsdag 10 oktober 2023 13:45
Aan: RedAndBundle/ForNAVSupport ***@***.***>
CC: Justin Aerts | Brabantplant ***@***.***>; Author ***@***.***>
Onderwerp: Re: [RedAndBundle/ForNAVSupport] Het aantal dagen tussen 2 datums weergeven (Issue #12)


Hoi, dat kan. Datum calculatie is niet super eenvouding in JavaScript dus je moet er waarschijnlijk wat moeite voor doen.

Wat probeer je precies te doen? Het verschil in dagen tussen 2 data? Welke source expressions zijn dat in ForNAV?

**Comment by Brabantplant** [comment]
![Schermafbeelding 2023-10-10 135005](https://github.com/RedAndBundle/ForNAVSupport/assets/147507969/9a4eb0b4-033a-4605-aec8-1a0bb585f83a)
Ik denk dat mijn afbeelding niet heeft geupload. Het gaat inderdaad om 2 datum velden.

**Comment by renebrummel** [comment]
Nu zie ik de afbeelding wel. We gaan er even naar kijken.

**Comment by Avatarum** [comment]
var D1 = new Date(MAWProductionControl.Date);
var D2 = new Date(MAWProductionControl.CustomColumn3);
// calculate diff in days
Math.round(Math.abs(D2 - D1) / (1000*60*60*24));  // round to 0 decimals, abs positive number,  divide by day in millisec

Set Format of the textbox  to number # to lose the decimals

**Comment by Brabantplant** [comment]
> var D1 = new Date(MAWProductionControl.Date); var D2 = new Date(MAWProductionControl.CustomColumn3); // calculate diff in days Math.round(Math.abs(D2 - D1) / (1000 * 60 * 60 * 24)); // round to 0 decimals, abs positive number, divide by day in millisec
> 
> Set Format of the textbox to number # to lose the decimals

This functioned! Thank you very much.
