### ISSUE TITLE
Problem with ReportForNav_GetPageNo

### ISSUE THREAD

**Issue by AnZa94** [RedAndBundle/ForNAVSupport#2]
Hello Rene,
i converted Reports from NAV2009 to BC14. Then i converted the Reports from C/SIDE to AL with the ForNAV Converter  and now i get this Issue.
![ReportForNAVPageNo](https://user-images.githubusercontent.com/62378630/95018034-29539200-065d-11eb-91fd-0b2935345a48.png)

Sincere regards,
Andre

**Comment by renebrummel** [comment]
Hi Andre,

The best fix would be to remove the column altogether and just use the CurrReport.Page from the Field List.

Best,
René

**Comment by AnZa94** [comment]
Good morning Rene,
thank you very much for your fast answer. 

Best regards,
Andre
