### ISSUE TITLE
connect is ok, why cannot open the report

### ISSUE THREAD

**Issue by wendywang303** [RedAndBundle/ForNAVSupport#4]
I have BC-14 container on local, connect is ok, but when I try to open the file show error, after go to my extension web client, try to open this report, show another error, how to fix this kind of error, thank you
![image](https://user-images.githubusercontent.com/34351232/97776614-f7d8c400-1b3f-11eb-80a4-d14079649431.png)
![image](https://user-images.githubusercontent.com/34351232/97776617-fe673b80-1b3f-11eb-81a9-aab10647393e.png)
![image](https://user-images.githubusercontent.com/34351232/97776621-045d1c80-1b40-11eb-8397-e0ba8ca4ff2e.png)

**Comment by wendywang303** [comment]
for the .Net framwork, I already UNLOCK in the dll file property, still show this error

**Comment by renebrummel** [comment]
First issue, you need a compiled app file in your extension path.
Second issue, you need to install the correct ForNAV version DLL in you add-ins folder of your service tier.
