### ISSUE TITLE
Hide the watermark via the request page?

### ISSUE THREAD

**Issue by AnZa94** [RedAndBundle/ForNAVSupport#5]
Good morning Rene,
is it possible to "hide" the watermark via the request page?
Is there a Property or something else?
ForNav  Cloud Version: 5.3.0.1

Best regards.
Andre

**Comment by renebrummel** [comment]
Hi Andre,

You can't on the std ForNAV reports. You will need to clone the report and add this request page option in AL if you want this functionality.

Best,
René

**Comment by AnZa94** [comment]
Hi Rene,
i forgot to tell you that this is an indi report. Is there a field or something similar that "controls" the watermark?

Best regards,
Andre

**Comment by renebrummel** [comment]
Hi Andre,

what do you mean with an ini report?

Best,
René

**Comment by AnZa94** [comment]
Hi Rene,
I mean a report in the range from 50000..

Best regards,
Andre

**Comment by renebrummel** [comment]
Got it.

You can set the watermark yourself in the code. If you copied a ForNAV report you'll find it. If you have a custom report you will need some code like this. If you want you can add a request page variable to enable or disable it.

    trigger OnPreReport()
    begin
        ;ReportsForNavPre;
        LoadWatermark();
    end;

    local procedure LoadWatermark()
    var
        ForNAVSetup: Record "ForNAV Setup";
        OutStream: OutStream;
    begin
        with ForNAVSetup do begin
            Get;
            CalcFields("Document Watermark");
            if not "Document Watermark".Hasvalue then
                exit;

            ForNavSetup."Document Watermark".CreateOutstream(OutStream);
            ReportForNav.Watermark.Image.Load(OutStream);
        end;
    end;

**Comment by AnZa94** [comment]
Good morning Rene,
thanks for the quick response. I used a ForNAV report as a template .I have probably not exactly checked the code .
Thanks for your help.

Best regards,
Andre
