### ISSUE TITLE
Hide the watermark via the request page? (the second :D)

### ISSUE THREAD

**Issue by AnZa94** [RedAndBundle/ForNAVSupport#6]
Good morning Rene,
I'm sorry but I expressed myself wrong. I put the watermark in the layout myself. In ForNAV I found a field for the visibility of the watermark. Can I use this in the code?
![image](https://user-images.githubusercontent.com/62378630/98215652-56d77800-1f48-11eb-94ef-4855e3e16e5c.png)

Best regards,
Andre

**Comment by AnZa94** [comment]
Hello again,
i have now added the programming to the "OnPreReport" trigger in the layout.  Are adjustments in the trigger ok or should one not adjust it?
![image](https://user-images.githubusercontent.com/62378630/98217800-4379dc00-1f4b-11eb-9ef5-ac9ccc89763b.png)
![image](https://user-images.githubusercontent.com/62378630/98217813-496fbd00-1f4b-11eb-890e-df6fcb985daa.png)
Best regards,
Andre

**Comment by renebrummel** [comment]
Hi Andre,

Yes, that should work. You can see the full set of watermark functions here:
https://fornav.github.io/ForNav.Guide/#/ForNAVForBCOnPrem/JavaScript

Best,
René

**Comment by AnZa94** [comment]
Hello again Rene,
I have an interesting behavior. 
The following facts: 
In the request page there is a boolean variable which is set to true in the "OnOpen" trigger.  
If I set it to false and look at the report the watermark is still visible. But if I print it or send it, it is without watermark. Is this a normal behaviour? 
If I comment out the line in the "OnOpen" trigger, the preview works correctly.
I hope it is written understandably :)

Best regards, 
Andre

**Comment by renebrummel** [comment]
First thing you need to check is if your report is calculating the watermark at all, it may be that the print function is preventing that.

Further without looking at the code I can't say. I would need tot try to recreate the code. It may be some time before I get to that.
